### ISSUE TITLE
Return value for function calls

### ISSUE THREAD

**Issue by camilstaps** [particle-iot/particle-cli#179]
Please set the bash return value after a function call to the return value of the function.

E.g., I have a function `setLed` on my device `futo`, and it only works with input `0` or `1`. Calling it with anything else results in a `-1` return value. However, the return value of the process is still `0`.

```
$ particle call futo setLed foo && echo $?
-1
0
```

If this would break things, could it be made a command line option? It would make shell scripts using the particle cli much neater.

**Comment by brycekahle** [comment]
To be clear, are you returning `-1` from your function? If so, returning a non-zero exit code when the function call succeeds would be misleading. We could certainly put this behind a command line option as an alternative.

**Comment by camilstaps** [comment]
@brycekahle thanks for your swift reply. Yes, I return `-1` from my function. That's what I'm using for some error (as suggested [here](https://docs.particle.io/reference/firmware/photon/#particle-function-)). 

I understand some people use this to return a meaningful value (for example, you could write a temperature function that returns the temperature), and this may break it. So yeah, a command line option would probably be better.

**Comment by brycekahle** [comment]
I like this idea but how will you know if the function call failed for some reason?

**Comment by brycekahle** [comment]
Maybe if you provide a value it uses that for the exit code in the failure case? Example: `particle call testphoton digitalwrite "D7,HIGH" --return-val -10` would return `-10` if it fails.

**Comment by brycekahle** [comment]
Another complication is exit codes are non-negative integers from `0` to `255`. So `-1` is not a valid exit code, and would instead be read as `255`.

**Comment by camilstaps** [comment]
> how will you know if the function call failed for some reason

For example in bash you could do `echo $?`. But also if you chain commands using `&&` it will have effect.

> Maybe if you provide a value it uses that for the exit code in the failure case?

That seems less flexible. If the return value from the function would be returned, you could return multiple status codes. I don't see what this would add, but do enlighten me.

Yeah, that exit codes range from 0 to 255 is an issue. I guess the most intuitive would be casting the return value to a `uint32_t` and then take the eight least significant bits.

**Comment by brycekahle** [comment]
The problem is knowing the difference between a failed function call (device is offline for example) and a function call that returns a non-zero return value.

**Comment by camilstaps** [comment]
As far as I can see, when the function call fails -1 is returned. So you could simply leave it to the developer to distinguish from it by not using -1 himself if he is going to use this feature.

**Comment by camilstaps** [comment]
Not needed any more.
