### ISSUE TITLE
Feature Req: Built-in Changelog

### ISSUE THREAD

**Issue by technobly** [particle-iot/particle-cli#202]
Just updated my CLI and had a fun idea.  Is it possible to add text output to the end of the installation/update log?  Maybe we could spit out the Changelog between the last two versions and which version you just upgraded to in there?

Additionally or instead of, how about building the changelog into the CLI?  so then you could do and get the same effect

```
npm update -g particle-cli && particle --changelog
```

**Comment by m-mcgowan** [comment]
we could use https://www.npmjs.com/package/changelog
