### ISSUE TITLE
Windows 10 - particle identify

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-cli#218]
gets the device id, then fails getting the system firmware version

**Comment by brycekahle** [comment]
What version of firmware were you running? Not all versions support that command.

**Comment by dmiddlecamp** [comment]
Looks like it happens in node 4.3.1, and node 0.12.4

![particlecliserialerrorsonwindows10node431](https://cloud.githubusercontent.com/assets/833793/13290772/ca5637d8-dada-11e5-948e-69f1cb7b8718.png)


![particlecliserialerrorsonwindows10](https://cloud.githubusercontent.com/assets/833793/13290775/cc2e4c44-dada-11e5-9f09-59033665f147.png)

**Comment by monkbroc** [comment]
I'm closing old issues.
