### ISSUE TITLE
[flashing] Check for file extension

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/particle-cli#223]
From the community:

`particle flash --serial test01.ino` is uploading the file to the device

http://community.particle.io/t/partice-cli-particle-flash-serial-test01-ino-not-working-as-expected/20647

**Comment by m-mcgowan** [comment]
What's the least surprising behaviour here?

1. have the file compiled in the cloud, and the binary flashed via serial
2. output a warning that the file is not a `.bin` file and refuse to flash

My vote goes on 1, since it's then very similar to `particle flash mydevice test01.ino`.

**Comment by m-mcgowan** [comment]
A documentation change in the CLI docs indicates that `particle serial flash` and `particle flash --serial` presently require a binary to flash.  Will keep this issue open because I feel that's only a stopgap - we can make flash to usb/serial/ota function similarly.

**Comment by kennethlimcp** [comment]
A little extended description of the flow would be like:

1.) check if Particle Device is available on serial, if so,
2.) compile code from cloud and flash via serial
3.) Otherwise inform the user that the device is not detected on serial
