### ISSUE TITLE
New out of box Photon detected as Core on Linux

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/particle-cli#226]
The `serialNumber: 'Particle_Photon'` doesn't match for a new photon straight out of the box since it has `'Spark_Devices_Photon'` as the serial number. Because of this, I can't set up a new Photon using the CLI.

**Comment by brycekahle** [comment]
Since you have the Linux box :smile: do you want to submit a PR?

**Comment by monkbroc** [comment]
Yeah. I just put that in so I don't forget about it.
