### ISSUE TITLE
particle-cli will send thousands of simultaneous API requests as fast as it can in some extreme scenarios

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-cli#233]
We've noticed some users have many thousands of devices registered to a single account.  A "particle list" will cause a giant spike of requests.  Can we set the connection pool on the request object to be like, 10, or rate-limit these requests, or cut-off the huge request spike after device number 100 or something unless a special flag is set?

**Comment by m-mcgowan** [comment]
Can we batch the API request into a single one to return info for many devices, rather than having one request per device?

Another alternative is to use pagination and filtering.
