### ISSUE TITLE
Explain required device mode per command in help

### ISSUE THREAD

**Issue by idokleinman** [particle-iot/particle-cli#242]
It might seem clear to us but not to our users and documentation is tricky - add simple explanation about required device mode per command in help, i.e.:

for `particle keys` - device needs to be in DFU mode
for `particle identify` - device needs to be in listening mode
for `particle list` - device should be claimed to appear and online to to get list of funcs/vars
etc etc

**Comment by monkbroc** [comment]
Good point. Long term I'd like most commands to work no matter the device mode (identify, wifi setup, flash) as long as it's connected to USB.

**Comment by m-mcgowan** [comment]
As a quick fix before we rework the device handling, adding the modes required in the command help would be a good start.
