### ISSUE TITLE
Flash says OK when required modules not present

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/particle-cli#246]
When compiling and flashing with
`particle flash --target 0.5.0 my_device application.cpp`
When the firmware on the device is old I get the message:
`Flash device OK:  Flash requires modules not present on device`

It shouldn't say OK if the flash didn't take place.

**Comment by m-mcgowan** [comment]
I couldn't reproduce this with a device running 0.5.3 and flashing a 0.6.0 app.
