### ISSUE TITLE
`particle subscribe mine` event stream times-out without error

### ISSUE THREAD

**Issue by technobly** [particle-iot/particle-cli#256]
The event stream in the CLI `particle subscribe mine` times out after awhile, but doesn’t terminate?  It appears to still be listening, but it’s deaf.

**Comment by brycekahle** [comment]
My times out after exactly 2 minutes consistently
```
time p subscribe mine
Subscribing to all events from my personal stream (my devices only)
Listening to: /v1/devices/events
particle subscribe mine  0.51s user 0.09s system 0% cpu 2:00.73 total
```

**Comment by m-mcgowan** [comment]
I'm not fully getting the context and what next steps might be. @technobly - what's the expected vs actual behaviour? Do we need to take any action here?

Steps to reproduce and a description of what's happening vs what's expected would be helpful. Thanks!

**Comment by monkbroc** [comment]
The issue is the subscribe command doesn't finish or reconnect after a network error.

Steps to reproduce:
- `particle subscribe mine`
- `particle publish --private foo`
- See the `foo` event in the subscribe terminal
- Turn off WiFi network then on
- Turn on WiFi network
- `particle publish --private foo`
- See that the `foo` event is missing in the subscribe terminal but the subscribe command continues.

**Comment by m-mcgowan** [comment]
Thanks, that's very clear!  What is the expected behaviour here? I imagine the subscribe command timing out immediately, or that it should attempt to reconnect to the event stream.

**Comment by monkbroc** [comment]
I would say reconnect the event stream. Transient HTTP errors happen and since `particle subscribe` is a long running command I would expect it to recover from those kinds of errors.

**Comment by m-mcgowan** [comment]
I reproduced this on OSX with 1.19.4. I had to leave the Wi-Fi disconnected for some time (over 2 minutes for sure.)

**Comment by dmiddlecamp** [comment]
hit this again today.  Subscribe to a feed, put your laptop to sleep, resume the next day (or sometime later), CLI is still running, but no events flow.  Would be interesting to see if we could detect that the socket was closed and resume it automatically after a short delay

**Comment by klaussner** [comment]
I ran into the same problem with `particle-api-js` (used by the CLI to create the event stream) and opened an issue with more details here: particle-iot/particle-api-js#95. :slightly_smiling_face:
