### ISSUE TITLE
colors look bad on a light terminal

### ISSUE THREAD

**Issue by tedder** [particle-iot/particle-cli#257]
The cli colors are hardcoded and assume a dark background. They aren't readable on a light background. The screenshot shows how it looks on Solarized Light.

This isn't an easy change because it's all through the code, but I still think it's worth having an issue for.

<img width="675" alt="colors on a light terminal backgorund" src="https://cloud.githubusercontent.com/assets/97914/15801629/54bb885a-2a50-11e6-9763-cff2e7c179a9.png">

**Comment by monkbroc** [comment]
What do other tools do to handle this? Do you simply turn off the color in tools like `ls`?

**Comment by tedder** [comment]
CLICOLOR=1 seems to do the trick for `ls`, not sure how it distinguishes light/dark, I don't have an `LSCOLORS` override. My `.vimrc` contains `set background=light`. `git` simply has color enabled.

Chalk doesn't support themes as easily as colors.js, but it appears to be *possible*, at least. It'd be a lot easier if all of p-cli's display code was wrapped, I think.

**Comment by monkbroc** [comment]
I agree this will be easier to customize when the CLI is more modularized.

**Comment by m-mcgowan** [comment]
I like the look of colors.js and the theming support, so that we can use named styles rather than raw colours. The system could provide a light/dark theme and try to make a sensible default choice, although the user can also specify the desired theme via env vars or a custom theme json file.

**Comment by m-mcgowan** [comment]
I use a white terminal with black text, which provides better contrast with the light grey text than the screenshot in the issue description.
