### ISSUE TITLE
Particle-CLI not working on ChromeOS/Chromebook Linux variant

### ISSUE THREAD

**Issue by faddah** [particle-iot/particle-cli#262]
hi,

i cannot get the particle-cli to work on my Chromebook running ChromeOS, which is a linux variant. i am in dev mode in my Chromebook and i can get to the command line and have installed node.js (v4.4.3) & npm (v3.8.6) and they run with several other NPM packages just fine, but particle-cli throws an exception during the set-up in the part when trying to find WiFi network. and the ChromeOS sees my WIFi and connects to it just fine, i am filing this bug issue on github right now from the Chromebook via my WiFi.

here is my set-up --

node.js v4.4.3
npm v3.8.6
particle-cli v1.14.2

acer Chromebook model #C720P-2600
ChromeOS - Version 51.0.2704.103 (64-bit)
Platform 8172.56.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.93.0
Channel of ChromeOS build - Currently on stable channel.
Webkit - 537.36 (@0)
V8 - 5.1.281.65

User Agent
Mozilla/5.0 (X11; CrOS x86_64 8172.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

Command Line

/opt/google/chrome/chrome --ppapi-flash-path=/opt/google/chrome/pepper/libpepflashplayer.so --ppapi-flash-version=22.0.0.192-r1 --ppapi-flash-args=enable_hw_video_decode=1 --enable-fixed-position-compositing --enable-impl-side-painting --max-tiles-for-interest-area=512 --ui-enable-per-tile-painting --ui-prioritize-in-gpu-process --use-gl=egl --gpu-sandbox-failures-fatal=yes --enable-logging --log-level=1 --use-cras --enable-wayland-server --user-data-dir=/home/chronos --max-unused-resource-memory-usage-percentage=5 --system-developer-mode --login-profile=user --has-chromeos-keyboard --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/oem_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/oem_small.jpg --default-wallpaper-is-oem --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --enable-prefixed-encrypted-media --enterprise-enrollment-initial-modulus=14 --enterprise-enrollment-modulus-limit=18 --vmodule=screen_locker=2,webui_screen_locker=2,lock_state_controller=2,webui_login_view=2,power_button_observer=2,_ui/display/chromeos_=1,_ash/display_=1,_ui/ozone_=1,_zygote_=1,_plugin_=2,_chromeos/login/_=1 --login-user=faddahyuetsu@gmail.com --login-profile=89829161a9bcda9d11fce00536e4549bbfab518f --flag-switches-begin --enable-sync-app-list --ignore-gpu-blacklist --flag-switches-end

Build Date
Thursday, June 16, 2016

for `$ cat /proc/version` i get ‒

```

Linux version 3.8.11 (chrome-bot@build67-m2) (gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_2d511e9_4.9.2-r122) ) #1 SMP Thu Jun 16 13:49:01 PDT 2016

```

issue ‒
when i attempt to do the particle-cli `particle setup` from the command line, here is what happens --

```

 $ particle setup
                  _   _      _        _
 _ __   __ _ _ __| |_(_) ___| | ___  (_) ___
| '_ \ / _` | '__| __| |/ __| |/ _ \ | |/ _ \
| |_) | (_| | |  | |_| | (__| |  __/_| | (_) |
| .__/ \__,_|_|   \__|_|\___|_|\___(_)_|\___/
|_|                     https://particle.io/

> Setup is easy! Let's get started...
> It appears as though you are already logged in as my_biz@me.com
? Would you like to log in with a different account? No

! PROTIP: Hold the MODE/SETUP button on your device until it blinks blue!
! PROTIP: Please make sure you are connected to the internet. 

> I have detected a Photon connected via USB.
? Would you like to continue with this one? Yes
Serial err: Error: Error: Permission denied, cannot open /dev/ttyACM0
Serial problems, please reconnect the device.
! The Photon supports secure Wi-Fi setup. We'll try that first.

! PROTIP: Wireless setup of Photons works like a wizard!
! PROTIP: We will automagically change the Wi-Fi network to which your computer is connected.
! PROTIP: You will lose your connection to the internet periodically.

! PROTIP: Some computers may require Administrator permissions for my automagical Wi-Fi scanning capabilities.

! OOPS: I was unable to scan for nearby Wi-Fi networks (-___-)

? We can still proceed in 'manual' mode. Would you like to continue? Yes

! PROTIP: Manual mode will prompt you to manage the Wi-Fi connection of your computer when it's necessary.
! PROTIP: To proceed, you will need to be able to manually change the Wi-Fi connectivity of your computer.
! PROTIP: Your Photon will appear in your computer's list of Wi-Fi networks with a name like, Photon-XXXX
! PROTIP: Where XXXX is a string of random letters and/or numbers unique to that specific Photon.

! PROTIP: You will need to know the password for your Wi-Fi network (if any) to proceed.
! PROTIP: You can press ctrl + C to quit setup at any time.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/nmcli ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

```

this happens each and every time with the same error in the same place. the error happens immediately after the pro-tips and exits to the command line, i never even get to use ctrl + C or anything like that.

any help please, in getting particle-cli to work correctly and set-up on my Chromebook?

thank you in advance.

best,

---  faddah
      portland, oregon, u.s.a.

**Comment by ScruffR** [comment]
For this problem, do you get the same outcome when you follow this suggestion given by CLI?

> PROTIP: Some computers may require Administrator permissions for my automagical Wi-Fi scanning capabilities.
so try
```text
sudo particle setup
```
And for only setting credentials I'd rather go with
```text
sudo particle serial wifi
```
for which you need to be in Listening Mode and don't use the auto-scanning feature, rather do it manually.

**Comment by monkbroc** [comment]
Hi @faddah, ChromeOS is not currently a platform we officially support for the CLI. If you're able to get it working, please let us know and contribute back your changes in a pull request.

**Comment by faddah** [comment]
@ScruffR & @monkbroc —

thank you for responding. 

unfortunately, now my Chromebook/linux variant is, on the shell command line tab, giving me an —

```

/bin/bash: symbol lookup error: /bin/bash: undefined symbol: rl_signal_event_hook

```

every time i start the shell tab and it no longer sees my node.js install and, consequently, any of the npm packages, including particle-cli. in addition, it's no longer giving me permissions to use gcc/make to re-install node. so i'll have to figure out what happened here and get it re-set. i'm afraid i can't be of much more use with this until i get the Chromebook working properly in dev mode and node.js & npm latest versions installed again.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by dbrgn** [comment]
I'm getting the same error on Arch Linux, with no network manager installed.

**Comment by monkbroc** [comment]
Can you suggest an alternative way to list and switch WiFi networks from the command line on your system?

**Comment by dbrgn** [comment]
Manually :) I use netctl with profile files. Just tell me to connect to a wifi network starting with a certain name and I can do that. Then ask to confirm on the command line.

**Comment by monkbroc** [comment]
Thanks for the explanation. I'll make sure the cli prompts for networks manually if the network manager isn't found. In the mean time you can do `particle serial identify` to get the device id, `particle serial wifi` to set the Wi-Fi password and `particle device add` to add the device to your account.

**Comment by dbrgn** [comment]
Thanks, good to know. I wasn't aware of `particle device add` and did the adding via the Android app instead :)
