### ISSUE TITLE
Better error message when failed attempt to upload public key to cloud

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/particle-cli#276]
Currently, failed attempts to upload a new device public key result in an `Error - undefined` message to the user, which is cryptic and unhelpful.

![image](https://cloud.githubusercontent.com/assets/1919681/18132433/da6ac96c-6f64-11e6-9acc-7ab61f8350d9.png)

See a community thread for another example:

https://community.particle.io/t/solved-cannot-connect-photon-blinking-cyan-with-red-flashes/19384/15

**Comment by m-mcgowan** [comment]
I couldn't reproduce this with `keys send`. What command did you use?

**Comment by monkbroc** [comment]
I used keys doctor I believe
