### ISSUE TITLE
'particle webhook list' missing webhooks in products

### ISSUE THREAD

**Issue by Here-Be-Dragons** [particle-iot/particle-cli#281]
What happens: when issuing `particle webhook list`, only webhooks external to a product are returned.  

Expected functionality: when issuing `particle webhook list`, webhooks loaded into a product should return along with webhooks not assigned to a specific product.

**Comment by monkbroc** [comment]
Thanks for reminding us of this. I know that the CLI has not been upgraded to be aware of products yet. That's on the todo list.

**Comment by jhlink** [comment]
Is there a timeline of when this feature will be available?

**Comment by kennethlimcp** [comment]
There's a much prettier UI available at https:/console.particle.io/integrations

**Comment by jhlink** [comment]
Thanks @kennethlimcp for the response!
It does work with products, although you have to create a product fleet in order to create a product specific webhook. I was just curious when the cli version of product webhooks would be available.

**Comment by monkbroc** [comment]
Kenneth is a member of the Particle community, but not an employee.

Product webhooks are on the roadmap for the CLI. We don't have a definite date for it but we know it's important to a lot of people.
