### ISSUE TITLE
check access token before API call

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/particle-cli#323]
```
KENMBP:test kennethlimcp$ pwc patch.json 
Error loading command /usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Module version mismatch. Expected 48, got 47.
Using settings from the file  patch.json
Sending webhook request  { uri: '/v1/webhooks',
  method: 'POST',
  json: 
   { },
  headers: { Authorization: 'Bearer' } }

! Please login - it appears your access token may have expired

Error Invalid token
KENMBP:test kennethlimcp$ p --version
1.19.0-libraries.20
```

**Comment by monkbroc** [comment]
This is a catch-22: there's no way to know that a token is expired before doing an API call, so the CLI has to go ahead and make the API call and reports the error if the token has expired.

**Comment by m-mcgowan** [comment]
I agree it's a catch 22 situation, although we may be able to offer a smoother experience. 

How about this:  in interactive mode, the CLI could catch the authentication error when running a command, prompt the user to login and then rerun the command entered. This provides a smoother experience. 

In non-interactive mode, it would fail as it does now. 

Another alternative is that we save the login credentials (securely) and automatically obtain a new access token when we detect it has expired.  I see pros and cons with this (smoother, but hiding the fact the token has expired), just throwing it out there for discussion.
