### ISSUE TITLE
Wrong error message during setup if token is expired

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/particle-cli#330]
When doing `particle setup` with an expired token, the message is:

```
! PROTIP: There was a network error while connecting to the cloud...
! PROTIP: We need an active internet connection to successfully complete setup.
! PROTIP: Are you currently connected to the internet? Please double-check and try again.
```

Doing `particle list` shows `! Please login - it appears your access token may have expired`

**Comment by m-mcgowan** [comment]
The current handling of the api is ad-hoc at best - each command is independently handling token expiration errors and such. 

Issue https://github.com/spark/particle-cli/issues/91 hints at having a single point of entry for handling login and access tokens.  For example, the command executor itself could catch exceptions from the API, and for authentication errors attempt to fix by using the retry_token or prompting the user to login (or failing in `--non-interactive` mode)

**Comment by m-mcgowan** [comment]
Similar to #45.

**Comment by stewartadam** [comment]
Just ran into this, `particle login` fixes it but would be great to have a more appropriate error message.
