### ISSUE TITLE
`particle nyan off` should restore `RGB.control()` state to prior value

### ISSUE THREAD

**Issue by machty** [particle-iot/particle-cli#344]
Please let me know if there's a better repo for this, but when I run the `nyan` command after doing `RGB.control(true)` in `setup`, it essentially does `RGC.control(false)` so it can shout rainbows but turning the `nyan off` reverts the LED back to pulsing cyan.

Expected behavior: it should revert to whatever the `.control()` value was before nyan mode was activated.

**Comment by kennethlimcp** [comment]
This is more of a firmware design to be changed as `nyan` was implemented way back in the days of the Spark Core where `RGB.control()` did not exist. :)

**Comment by m-mcgowan** [comment]
@machty You might try upgrading to 0.6.0 since the LED code was reworked considerably in that version.
