### ISSUE TITLE
Feature Request: Commands to display info for a library

### ISSUE THREAD

**Issue by nrobinson2000** [particle-iot/particle-cli#359]
I think It would be great if there were commands to get the metadata for a library, like the Github URL, Author, Description, and Stats just like you can get from the Web IDE.  It would be best if there were options to get only a specific field.

The command could be `info`, and one would be able to use it through:

```
particle library info NAME_OF_LIB
```

Flags could be used to explicitly request certain fields.  For example if you wanted to find the Github URL for the `neopixel` library you could use:

```
particle library info neopixel --url
```

And particle-cli would output only `https://github.com/technobly/Particle-NeoPixel`, for ease of use with scripts like [po-util](https://github.com/nrobinson2000/po-util).

I really like using Particle Libs 2.0, and I feel like the `info` command is a required feature.

---
*Credit: @mrmowgli for suggesting that I make this feature request.*

**Comment by monkbroc** [comment]
Very good idea. Thanks for the nice spec Nathan!

**Comment by nrobinson2000** [comment]
@monkbroc Thanks for the support.  I hope this won't be too difficult to implement.

**Comment by nrobinson2000** [comment]
I would try to implement this myself, but I'm terrible with NodeJS, but I want to learn it.

I presume the command could use the library API to get the info: https://docs.particle.io/reference/api/#libraries

**Comment by nrobinson2000** [comment]
Any updates on this?

**Comment by monkbroc** [comment]
We are tracking this task but have not started the development yet.

**Comment by nrobinson2000** [comment]
Awesome.

**Comment by nrobinson2000** [comment]
I've now made this a feature of po-util.  Using the following function, po-util will attempt to find the URL of a library, and if it is a github link it will ask you if you'd like to download the library repository using git instead of downloading a release with particle-cli:

```bash
getLibURL()
{
  TOKEN="$(cat ~/.particle/particle.config.json | grep 'token' | grep -oE '([0-Z])\w+' | grep -v 'token')"
  DATA=$(curl -sLH "Authorization: Bearer $TOKEN" "https://api.particle.io/v1/libraries/$1" | json_pp)
  LIBURL=$(echo "$DATA" | grep "url" | grep -oE '"((?:\\.|[^"\\])*)"' | grep "http" |  tr -d '"')
}
```

Here is how/where `getLibURL` is actually used within po-util when downloading a library:
```bash
if  ( echo "$LIBURL" | grep "github" ) > /dev/null ;
then
  green_echo "$LIB_QUERY is availiable on GitHub!"
  read -rp "Would you prefer to download it this way? (yes/no): " answer

  if [ "$answer" == "yes" ] || [ "$answer" == "y" ] || [ "$answer" == "Y" ];
  then
    echo
    cd "$LIBRARY"
    git clone "$LIBURL" "$LIB_QUERY"
    echo
    blue_echo "Downloaded $LIB_QUERY from GitHub."
    return 0
  fi
  echo
fi
```

**Comment by nrobinson2000** [comment]
Here is a snippet for searching for a library's GitHub URL quickly if anyone is looking for it.

https://gist.github.com/nrobinson2000/f77a32c04c2fb9540c658a17009276f4
