### ISSUE TITLE
Tab completion would be a cool feature

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-cli#369]
Looks like we should export our commands and argument structure, and let bash perform tab completion?

Looks like the ARM mbed folks do a good job of this here -> https://github.com/ARMmbed/mbed-cli/tree/master/tools/bash_completion

**Comment by nrobinson2000** [comment]
I've just found out how to do bash completion for po-util and I'll see if I can start a bash completion for particle-cli.

**Comment by nrobinson2000** [comment]
I've started a bash completion with the basic particle commands:
https://github.com/nrobinson2000/particle-cli-completion

**Comment by nrobinson2000** [comment]
Sorry, to bump the thread, but I've created a python script to generate the bash completion script, and it works very well:
https://github.com/nrobinson2000/particle-cli-completion/blob/master/generator/generate.py

The generated script can be found here:
https://github.com/nrobinson2000/particle-cli-completion/blob/master/particle-cli
