### ISSUE TITLE
DeviceID with uppercase hex digits isn't recognized

### ISSUE THREAD

**Issue by embedded-creations** [particle-iot/particle-cli#370]
I experienced this issue in my Product's Devices page, but I was directed to report it here.  It's probably an issue in other parts of Particle tools as well, but I haven't tested.

I'm trying to add a device. I got the device ID from `dfu-util -l`, which returns an all-caps ID:

e.g. `2A0048000000000000000000`

If I try to "Add One Device" and paste in that number, I get: "Bummer! No devices were added to your product. Please double check the device IDs are correct and try again."

If I change the uppercase "A" to a lowercase "a", I can add the deviceID:

e.g. `2a0048000000000000000000`

Please fix this. We're planning to use this workflow to add hundreds of Electrons to our product, and having to add an extra step to convert any uppercase letters to lowercase is just going to slow things down.

**Comment by kennethlimcp** [comment]
@jme783
