### ISSUE TITLE
cannot kill the serial monitor in follow mode with CTRL-C

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-cli#372]
If the follow mode has disconnected / reconnected to a device after it resets, you can no longer kill the serial monitor with CTRL-C / keyboard interrupts.

**Comment by technobly** [comment]
I've seen this before and when that happens CTRL+Z seemed to work.  I just tried reproducing this though and could not, perhaps this is fixed?
```
Opening serial monitor for com port: "/dev/tty.usbmodem142421"
Serial monitor opened successfully:
Serial connection closed.  Attempting to reconnect...
Serial monitor opened successfully:
// CTRL+C
^CCaught Interrupt.  Cleaning up.
Serial connection closed.
```
