### ISSUE TITLE
Allow login with a token

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/particle-cli#374]
For automated scripts, it would be helpful to do `particle login --token abcd123456` and have the CLI use that token directly. The current workaround is to create a JSON profile file with the token. It requires detailed knowledge of how the CLI stores profiles.

**Comment by nrobinson2000** [comment]
>The current workaround is to create a JSON profile file with the token. It requires detailed knowledge of how the CLI stores profiles.

That's not too difficult actually, and can be done with a bash function to put in an automated script:

```bash
loginWithToken() # $TOKEN $EMAIL
{
  local TOKEN EMAIL
  TOKEN="$1"
  EMAIL="$2"

  cat << EOF > "$HOME/.particle/particle.config.json"
{
  "access_token": "$TOKEN",
  "username": "$EMAIL"
}
EOF

}

```

**Comment by nikeee** [comment]
I think this is currently supported the way you requested:
```shell
particle login --token <token>
```
