### ISSUE TITLE
Allow skipping bandwidth prompt for Electron flash

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/particle-cli#382]
Add a --force flag to particle flash to skip the prompt for Electron bandwidth

**Comment by technobly** [comment]
+ 💯

**Comment by andrewwatson** [comment]
yay!

**Comment by m-mcgowan** [comment]
this has been implemented - https://github.com/spark/particle-cli/commit/21e212be623f8503efca99512f6985231b2c0323

**Comment by andrewwatson** [comment]
I just installed 1.24.1 but this doesn't seem to work.  maybe i'm doing it wrong?

```
particle flash --yes ${DEVICE} firmwares/latest.bin
```

**Comment by monkbroc** [comment]
Try `particle flash ${DEVICE} firmwares/latest.bin --yes`

**Comment by andrewwatson** [comment]
I tried that but i got this output:

```
$ particle flash <redacted> firmwares/latest.bin --yes
no files included?
```

and firmwares/latest.bin is definitely there because if i remove the --yes it works fine

**Comment by mikeyyuen** [comment]
Does there need to be a filter added here?

https://github.com/spark/particle-cli/blob/21e212be623f8503efca99512f6985231b2c0323/commands/CloudCommands.js#L246
