### ISSUE TITLE
doctor: display system firmware 

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/particle-cli#385]
Story:

User uses `particle device doctor` to restore a device to its healthy state but realizes that old user code no longer runs (aka safe mode). 

Solution:

CLI should display the system version that is used to restore the device for clarity.

**Comment by monkbroc** [comment]
I'm not sure I understand the scenario. The device doctor puts the latest released system firmware and replaces the user application with Tinker. In what situation does this lead to safe mode?

**Comment by kennethlimcp** [comment]
Oh yes, i thought of that as well. It might be like firmware is compiled using `0.7.1-rc.1` but the latest stable firmware is `0.7.0` and the user went to OTA the firmware with system version selected as `0.7.1-rc.1` after device is healthy.

**Comment by monkbroc** [comment]
Hum, I'm not super worried about that. Release candidate testers are advanced users that know how to handle this case. @technobly what do you think?
