### ISSUE TITLE
CLI needs different error message for API errors

### ISSUE THREAD

**Issue by towynlin** [particle-iot/particle-cli#387]
I observed during an API deploy today that my CLI (version 1.24.0) briefly output "No devices found." for a `particle list` command. I have many devices in my account that were returned as normal both before and after the ephemeral failure. I suspect that it received an HTTP error response from the API. If so, that should output a different error message, for example, "There was an API error. Please try again."

Thoughts @beriberikix?

**Comment by beriberikix** [comment]
Do we actually know what the error was? Definitely haven't a default unknown error would be better than displaying the wrong error.

**Comment by monkbroc** [comment]
The error was likely 502 Bad Gateway.

Steps to reproduce:
1. Run `ngrok http 3000`
2. `cp ~/.particle/particle.config.json ~/.particle/broken.config.json`
3. `particle config broken`
4. `particle config broken apiUrl https://29e51a2c.ngrok.io` (use the hostname from ngrok)
5. `particle list`

Actual output: No devices found.

Expected output: display a human readable error to the user

**Comment by beriberikix** [comment]
More n00b questions: where is the output sourced from? Is it a lookup table in the CLI? Passed through via the API? Combination? Is there a verbose mode for the CLI that could display the user friendly message and a system message if needed?

**Comment by monkbroc** [comment]
There's no consistent handling of API errors in the CLI. Each command deals with errors in different ways: stack trace, silently ignore, human readable message.

There was discussion of a `--json` flag to make the output machine consumable. Other ideas are welcome.

**Comment by technobly** [comment]
I ran into the same issue today, and discovered a new corner case in the CLI.  If you try to logout/login when the API is down/being updated, the CLI will tell you you are logged in successfully even though there is no way that can be true.
