### ISSUE TITLE
Missing documentation and help for multiple options 

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/particle-cli#399]
Over time more and more options found their way into CLI but the online docs and inline help have not kept up with it.
One such example is `particle serial claim` which does not disclose the argument syntax but only says
"`claimCode required`" although it's provided, so I'd guess some other argument is needed, but which is not said.
Instead of "`claimCode required`"  (or any other nondescript message for other errors) a full syntax example should be stated for each comman that demands arguments and isn't satisfied with the provided list of arguments.

See here
https://community.particle.io/t/cli-particle-serial-claim-looking-for-syntax-please/38849/3

**Comment by monkbroc** [comment]
The root of the problem is that argument parsing is ad-hoc and implemented in each command. I'm working on porting all commands to use a single argument parser. It will make the help text more consistent. I'll also add better examples for each command.

**Comment by ScruffR** [comment]
@monkbroc, can you chime in on the thread above how `particle serial claim` should be called?

**Comment by monkbroc** [comment]
The help is more helpful in 1.29.0. Regarding the claim command being hard to use, I opened a separate issue https://github.com/particle-iot/particle-cli/issues/424
