### ISSUE TITLE
CLI (or library mamagement in general) fails to provide the correct error on lib upload

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/particle-cli#400]
As seen in this thread
https://community.particle.io/t/particle-library-upload-fails/38879/9?u=scruffr

For some reason trying to upload a library with a name that (possibly) exists as private lib already caused an obscure error message 
```
This library could not be imported. Try another library or try this one again later.
```
instead of the more explicit `You are not the owner of this library` message I've seen before.

**Comment by JelmerT** [comment]
Just came across the same issue. +1
