### ISSUE TITLE
`particle serial wifi credentials.json` not recognized in newest version 1.28.1

### ISSUE THREAD

**Issue by technobly** [particle-iot/particle-cli#404]
These commands use to work and now the credentials.json is not recognized:
```
$ echo '{"network":"my_ssid","security":"WPA2_AES","password":"my_password"}' > credentials.json
$ particle serial wifi credentials.json
$ particle serial wifi --port /dev/cu.usbmodem141421 credentials.json
```

**Comment by monkbroc** [comment]
Hum. I didn't realize this ever worked. I can't make it work with the exact same syntax since the filename was not a documented command line parameter. Would it be OK to add this functionality back using a flag like `--credentials wifi.json`?

**Comment by technobly** [comment]
What about `--file` so it could be reused for other commands?  I know most other commands don't need that though that take files as an option, but it could be an alternate explicit way to do it.  Just wondering if file input will come up again.  I'm totally fine with whatever though, as long as that great feature comes back :)
