### ISSUE TITLE
REQ: When flashing firmware via ymodem `--serial`, allow selection of `--port`

### ISSUE THREAD

**Issue by technobly** [particle-iot/particle-cli#406]
I have all of my USB hubs labeled and aliased so that I can easily do things like substitute `$port10p` for `/dev/cu.usbmodem1424441` and then it's really handy for commands that support port specification like `particle serial monitor --port $port10p` when you have a bazillion devices connected.

This feature doesn't seem to be supported with the `flash --serial` command which uses USB serial ports.  Please add it :)

```
$ particle flash --serial ../build/releases/0.7.0/system-part1-0.7.0-electron.bin --port $port10p
! PROTIP: Hold the SETUP button on your device until it blinks blue!
? Press ENTER when your device is blinking BLUE 
? Which device did you mean? 
  /dev/tty.usbmodem142431 - Photon 
  /dev/tty.usbmodem14231 - Core 
  /dev/tty.usbmodem14221 - Photon 
❯ /dev/tty.usbmodem1424441 - Electron 
  /dev/tty.usbmodem1424421 - Electron 
  /dev/tty.usbmodem1424411 - Electron 
  /dev/tty.usbmodem142421 - Photon 
(Move up and down to reveal more choices) ... too many!
```

**Comment by monkbroc** [comment]
Fixed in 1.31.0. Try it with `npm install -g https://github.com/particle-iot/particle-cli/releases/download/v1.31.0-rc.2/particle-cli-1.31.0-rc.2.tgz`
