### ISSUE TITLE
[FEATURE REQUEST] Here document support for particle serial wifi?

### ISSUE THREAD

**Issue by nrobinson2000** [particle-iot/particle-cli#412]
It would be great if [Here Documents](http://www.tldp.org/LDP/abs/html/here-docs.html) were supported by `particle serial wifi --file`. That way I would have a more reliable method for setting up devices from within scripts.

With Here Document support I would be able to do something like:

```
particle serial wifi --file << PARTICLEWIFI
{
  "network": "my_ssid",
  "security": "WPA2_AES",
  "password": "my_password"
}
PARTICLEWIFI
```
----
Discussion on Particle community:
https://community.particle.io/t/feature-request-here-document-support-for-particle-serial-wifi/41396?u=nrobinson2000

**Comment by technobly** [comment]
You can do this already in v1.29.0 :-) Check out this other isssue for some docs, https://github.com/particle-iot/particle-cli/issues/404

**Comment by nrobinson2000** [comment]
But that still requires you to make the credentials.json file. I know this is nitpicky but it would be a good feature.

**Comment by bkobkobko** [comment]
I think the feature is reading the JSON file from stdin, rather that from an actual file.  In normal Un*x you might do something like this:
```
echo '{"network":"said"...} | particle serial wifi --file -
```

**Comment by nrobinson2000** [comment]
Exactly. Support for reading the JSON from stdin would support the method you mentioned and it would support heredoc's.

**Comment by monkbroc** [comment]
That's an good suggestion. Thanks @nrobinson2000 for the suggestion and @bkobkobko for clarifying!
