### ISSUE TITLE
feature request: param to avoid blocking on waiting for user to press ENTER

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-cli#413]
When using serial flash, I need to be able to script flashing a device without a user hitting enter since I'm using the baud mode to pull the device into the right state, 

demo code:
===
```
#force device into serial mode with baud 28800
particle flash --serial some_firmware.bin
```
**observed behavior: CLI prompts user to hit ENTER**

desired code:
===
```
#force device into serial mode with baud 28800
particle flash --serial some_firmware.bin --force
```
**expected behavior: CLI behaves as if someone hit enter to the prompt**

**Comment by technobly** [comment]
Can we use both for all auto completion going forward so as not to break existing scripts?

You can also currently simulate pressing enter with
`yes “” | particle flash --serial firmware.bin`

**Comment by dmiddlecamp** [comment]
any thoughts about if we could get this on the roadmap, or a particular milestone for future development?
