### ISSUE TITLE
Windows installer detected as Malware

### ISSUE THREAD

**Issue by antoniovazquezblanco** [particle-iot/particle-cli#416]
Some antivirus detect the windows installer as malware.
See: https://www.virustotal.com/#/file/e43b23c062130fadf9c1d24d516534500920e1f52e20620b01ccb5632e538fb2/detection

A couple of days ago the installer could not be accesed in my university due to this issue.

**Comment by monkbroc** [comment]
That's unfortunate. I'm not sure what we can do about it at this time since only a couple AV vendors are reporting a false positive for this program.

**Comment by beriberikix** [comment]
At least for McAfee we can submit a [report](https://kc.mcafee.com/corporate/index?page=content&id=KB83659). I'll submit and let you know how it goes.

**Comment by antoniovazquezblanco** [comment]
Results have changed. Now trendmicro (AV in my institution) now reports the installer as it has previously done locally. AVG seems no longer flagging the file as a virus.

**Comment by monkbroc** [comment]
I'll close this for now then. Let us know if it comes back.
