### ISSUE TITLE
particle-cli update/install fails with node 12. Node-gyp need to be updated

### ISSUE THREAD

**Issue by junior** [particle-iot/particle-cli#508]
Currently the update and install fails if used the [**current** version](https://nodejs.org/en/about/releases/) of node (12).

node-gyp need to be updated to work with node 12 and its dependencies like NAN that needs to be 2.3+.

**Comment by busticated** [comment]
yep, it's on my list here. some background here 👉 https://github.com/particle-iot/particle-cli/pull/486

**Comment by junior** [comment]
Just updating the node port would be enough?

**Comment by nikeee** [comment]
I think this was fixed in #509.

**Comment by busticated** [comment]
this should be fixed as of https://github.com/particle-iot/particle-cli/pull/509

i've released `2.0.0-rc.0` based on the `feature/v2` branch and associated PR https://github.com/particle-iot/particle-cli/pull/537

it adds official support for `node@12` and drops support for `node@6`

you can install it by running `npm i particle-cli@next`

i'm closing this out but feel free to chime in over in the aforementioned PR :+1:
