### ISSUE TITLE
GCC upgrade plans in Cloud Compile

### ISSUE THREAD

**Issue by nikeee** [particle-iot/particle-cli#526]
As far as I can tell, the cloud compile feature uses GCC 5 under the hood. This compiler version is four years old and does not support C++14 onwards (only C++11).

Are there any plans to upgrade to a newer GCC? The current version is 9.2. The device-os seems to be compatible with a newer GCC.

**Comment by busticated** [comment]
it's on our road-map here but no target launch date as of yet
