### ISSUE TITLE
Compile failed: Provide platform for compiling

### ISSUE THREAD

**Issue by brendonparker** [particle-iot/particle-cli#572]
## Description

When I try to compile from the CLI, I get: `Compile failed: Provide platform for compiling`

### Steps to reproduce

```
git clone https://github.com/ljezny/Particle-HAP
cd Particle-HAP/examples/lightbulb
particle compile core
```

### Environment

Tell us about your setup:

* OS: OSX
* Node (run `node -v`): v10.20.1
* NPM (run `npm -v`): 6.14.4
* Particle CLI (run `particle version`): 2.3.0

**Comment by busticated** [comment]
see https://github.com/particle-iot/particle-cli/pull/569

fix will ship soon but no specific ETA
