### ISSUE TITLE
Add a particle cli command for clearing wifi credentials

### ISSUE THREAD

**Issue by antoniovazquezblanco** [particle-iot/particle-cli#597]
## Description

Add a command such as `particle serial wifi --clean` to delete existing wifi credentials.

### Motivation

This avoids the need to use the buttons of a device in my workflow when claiming multiple devices.

**Comment by derrickrc** [comment]
Any update on this?

**Comment by antoniovazquezblanco** [comment]
https://github.com/particle-iot/particle-cli/pull/605
