### ISSUE TITLE
Auto connect on Windows

### ISSUE THREAD

**Issue by brycekahle** [particle-iot/particle-cli#97]
It appears we can do this with `netsh`, but we may have to create a "profile". The [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa369853%28v=vs.85%29.aspx) has a bunch of samples. Perhaps we should roll the connect functionality in with `node-wifiscanner` and create a `node-wifi` module?

[netsh documentation](https://technet.microsoft.com/en-us/library/Cc755301%28v=WS.10%29.aspx)

**Comment by m-mcgowan** [comment]
Bryce, I'm not sure I understand what's being requested here. Could you provide some more context please.

**Comment by brycekahle** [comment]
On macOS we can automatically connect to a Wi-Fi network, but we cannot on Windows right now. It is possible, but requires some research and testing. The links above are a starting point.

**Comment by m-mcgowan** [comment]
Thanks. related to #258.
